FROM python:3.10.13
RUN apt-get update --fix-missing
WORKDIR /app
COPY ./src/* ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
RUN git clone https://github.com/PKU-YuanGroup/MoE-LLaVA
WORKDIR /app/MoE-LLaVA
RUN pip install -e .
RUN pip install -e ".[train]"
RUN pip install flash-attn --no-build-isolation
WORKDIR /app
CMD ["uvicorn", "server:app", "--host", "::", "--port", "80", "--log-level", "info"]